package com.weavr.api.pipeline.ocr;

import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Duration;
import java.util.List;

import com.weavr.api.pipeline.ExternalProcess;
import com.weavr.api.pipeline.audio.FfmpegProperties;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;
import org.junit.jupiter.api.io.TempDir;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * The visual tier against the <b>real</b> ffmpeg and the <b>real</b> tesseract.
 *
 * <p>Opt-in, because it needs both binaries on PATH:
 *
 * <pre>
 *   WEAVR_LIVE_OCR=1 ./mvnw test -Dtest=OcrLiveTest
 * </pre>
 *
 * <p><b>Why this exists, given 47 mocked tests already pass.</b> Three times now
 * this repo has shipped a green mocked suite over a real defect: 27 tests missed
 * three yt-dlp bugs, 67 missed a UTF-8 decoding bug, and every test in the
 * project missed a missing dependency that stopped the app booting. A mocked
 * {@code ExternalProcess} cannot tell you whether an ffmpeg filter graph selects
 * any frames or whether tesseract accepts the flags you passed it — those are
 * facts about the binaries, and only the binaries know them.
 *
 * <p>It deliberately needs <b>no network</b>: the fixture video is generated by
 * ffmpeg itself, so this is a genuine end-to-end check of the tier that can also
 * run in a container build. What it does not cover is real-world visual noise —
 * text over video, motion blur, stylised fonts, low contrast. That is what the
 * thirty-Reel eval set is for, and no synthetic fixture substitutes for it.
 */
@EnabledIfEnvironmentVariable(named = "WEAVR_LIVE_OCR", matches = "1")
class OcrLiveTest {

    private static final String FFMPEG = System.getenv().getOrDefault("WEAVR_FFMPEG_BINARY", "ffmpeg");
    private static final String TESSERACT =
            System.getenv().getOrDefault("WEAVR_TESSERACT_BINARY", "tesseract");

    /** Whatever bold sans the host has; the text matters, the typeface does not. */
    private static final String FONT = System.getenv()
            .getOrDefault("WEAVR_LIVE_FONT", "C\\:/Windows/Fonts/arialbd.ttf");

    private final ExternalProcess processes = new ExternalProcess();

    private static OcrProperties properties() {
        return new OcrProperties(true, TESSERACT, "eng", 6, Duration.ofSeconds(60),
                90, 12, 0.25, 150, null, 60.0, 8, 0.5, 2, false, 4);
    }

    private FrameExtractor extractor() {
        return new FrameExtractor(processes,
                new FfmpegProperties(FFMPEG, Duration.ofSeconds(120)), properties());
    }

    /**
     * A static overlay card: white text on near-black, no motion, no cuts — the
     * exact content the whole tier exists for, and the exact content the
     * obvious filter chain returns nothing for.
     */
    private Path renderCard(Path dir) {
        String drawText = String.join(",",
                draw("CREAMY TOMATO PASTA", 34, 120),
                draw("400g rigatoni", 28, 260),
                draw("2 tbsp olive oil", 28, 320),
                draw("1 cup heavy cream", 28, 380),
                draw("3 cloves garlic", 28, 440));

        ExternalProcess.Result result = processes.run(List.of(
                FFMPEG, "-y", "-nostdin", "-loglevel", "error",
                "-f", "lavfi", "-i", "color=c=#1a1a2e:s=480x854:d=12:r=30",
                "-vf", drawText,
                "-c:v", "libx264", "-pix_fmt", "yuv420p",
                dir.resolve("card.mp4").toString()), Duration.ofSeconds(120));

        assertThat(result.succeeded())
                .as("fixture render failed: %s", result.stderr())
                .isTrue();
        return dir.resolve("card.mp4");
    }

    private static String draw(String text, int size, int y) {
        return "drawtext=fontfile='%s':text='%s':fontcolor=white:fontsize=%d:x=60:y=%d"
                .formatted(FONT, text, size, y);
    }

    /**
     * The end-to-end pass: video in, ingredient list out, no model call.
     * This is Phase 4's exit criterion in one assertion.
     */
    @Test
    void readsAnOverlayOnlyCardEndToEndWithNoModelCall(@TempDir Path dir) {
        Path video = renderCard(dir);

        FrameExtractor.Keyframes frames = extractor().extract(video, dir);
        assertThat(frames.isEmpty())
                .as("a static card must still yield frames — this is the whole trap")
                .isFalse();
        assertThat(frames.colour()).hasSameSizeAs(frames.ocr());

        OcrProperties props = properties();
        TesseractClient tesseract = new TesseractClient(processes, props);
        FrameTextVoter.VotedText voted = new FrameTextVoter(props).vote(tesseract.readAll(frames.ocr()));

        assertThat(voted.text()).isNotBlank();
        assertThat(voted.text().toLowerCase())
                .contains("rigatoni")
                .contains("olive oil")
                .contains("heavy cream")
                .contains("garlic");
        // Quantities are the part an LLM cannot reconstruct from context, so
        // reading them correctly is what separates a usable recipe from an
        // invented one.
        assertThat(voted.text()).contains("400g").contains("2 tbsp").contains("1 cup");

        OcrQualityGate.Decision decision = new OcrQualityGate(props).judge(voted);
        assertThat(decision.verdict())
                .as("clean synthetic text must clear the gate, or the floor is set wrong: %s",
                        decision.reason())
                .isEqualTo(OcrQualityGate.Verdict.PASS);
    }

    /**
     * The negative case, and the one that decides whether users get invented
     * ingredients.
     *
     * <p>Run against a real 90-second talking-head video, tesseract reads the
     * background as tokens like {@code |} at confidence 72, {@code =} at 91 and
     * {@code —} at 74 — <b>confident</b> symbol soup, not a low-confidence
     * signal anyone could filter on. A gate watching confidence alone would
     * wave that straight through to the model, which would then classify it
     * into something plausible. The alphabetic-ratio signal is what catches it,
     * and this pins that it does.
     */
    @Test
    void doesNotPassTextlessVideoOffAsAnExtraction(@TempDir Path dir) {
        // Moving noise: no text anywhere, but plenty for tesseract to
        // hallucinate punctuation out of — the same shape as film grain,
        // foliage and out-of-focus background in a real clip.
        ExternalProcess.Result render = processes.run(List.of(
                FFMPEG, "-y", "-nostdin", "-loglevel", "error",
                "-f", "lavfi", "-i", "color=c=gray:s=480x854:d=8:r=30,noise=alls=60:allf=t+u",
                "-t", "8", "-c:v", "libx264", "-pix_fmt", "yuv420p",
                dir.resolve("noise.mp4").toString()), Duration.ofSeconds(120));
        assertThat(render.succeeded()).as("fixture render failed: %s", render.stderr()).isTrue();

        FrameExtractor.Keyframes frames = extractor().extract(dir.resolve("noise.mp4"), dir);
        OcrProperties props = properties();
        FrameTextVoter.VotedText voted = new FrameTextVoter(props)
                .vote(new TesseractClient(processes, props).readAll(frames.ocr()));

        assertThat(new OcrQualityGate(props).judge(voted).passed())
                .as("textless video must not pass the gate; it read: %s", voted.text())
                .isFalse();
    }

    /**
     * Pins the defect that running the real binary found.
     *
     * <p>{@code select='gt(scene,0.25)',mpdecimate} — the chain the plan
     * specifies, and the one every tutorial gives — selects <b>zero</b> frames
     * from a static card, because frame 0 has no predecessor to differ from and
     * nothing afterwards changes. Measured: 0 frames from that chain, 1 from
     * ours, on the same 12-second fixture. If someone ever "simplifies" the
     * selector back, this fails.
     */
    @Test
    void sceneDetectionAloneSelectsNothingFromAStaticCard(@TempDir Path dir) {
        Path video = renderCard(dir);
        Path naive = dir.resolve("naive");
        Path ours = dir.resolve("ours");
        assertThat(naive.toFile().mkdirs()).isTrue();
        assertThat(ours.toFile().mkdirs()).isTrue();

        processes.run(List.of(
                FFMPEG, "-y", "-nostdin", "-loglevel", "error", "-i", video.toString(),
                "-vf", "select='gt(scene,0.25)',mpdecimate",
                "-fps_mode", "vfr", "-frames:v", "12",
                naive.resolve("f-%03d.jpg").toString()), Duration.ofSeconds(120));

        assertThat(countFiles(naive))
                .as("if this is ever non-zero, the trap is gone and the extra selector terms can go too")
                .isZero();

        assertThat(extractor().extract(video, ours).size()).isPositive();
    }

    private static long countFiles(Path dir) {
        try (var files = Files.list(dir)) {
            return files.filter(Files::isRegularFile).count();
        } catch (Exception e) {
            throw new AssertionError("could not list " + dir, e);
        }
    }
}
